# Utiliza la imagen oficial de Tomcat como base
FROM tomcat:9.0.84-jdk21-temurin

# Copia tu archivo WAR desde el directorio del proyecto al directorio webapps de Tomcat
COPY JCSG-CRUD.war /usr/local/tomcat/webapps/
